Repository nv-legate/legate.core, pull requests merged in 2022-12, with the labels that each got.

#505 Add CTK 11.8 to environment generation script
  scripts/generate-conda-envs.py
Labels: category:task

#500 Add machinery for legate.core base tests
  .github/workflows/ci.yml
  tests/unit/legate/driver/test_main.py
  tests/unit/legate/jupyter/test_main.py
  tests/unit/legate/tester/test_config.py
  tests/unit/legate/util/test_system.py
Labels: category:task

#506 Fix non-CUDA build
  src/core/task/return.cc
Labels: category:task

#507 legate/core: reset storage key partition in Store::reset_key_partition
  legate/core/store.py
Labels: category:task

#508 Don't nocr for single node
  legate/driver/config.py
  tests/unit/legate/driver/test_command.py
  tests/unit/legate/driver/test_config.py
Labels: category:task

#510 Fix for 509
  legate/core/solver.py
Labels: category:improvement

#514 Fix uninstall instructions for jupyter extension
  legate/jupyter/kernel.py
Labels: category:task

#515 Change the default Legion branch to collective
  install.py
Labels: category:task

#517 Improve build documentation
  BUILD.md
  README.md
  scripts/generate-conda-envs.py
Labels: category:improvement

#511 Implementin logic for reuse of reduction instances
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
  src/core/mapping/instance_manager.cc
  src/core/mapping/instance_manager.h
Labels: category:new-feature

#520 Sharding functor for delinearizing functor
  legate/core/projection.py
  legate/core/transform.py
  src/core/runtime/projection.cc
Labels: category:task

#466 New collective
  cmake/Modules/legate_core_options.cmake
  cmake/thirdparty/get_legion.cmake
  legate_core_cpp.cmake
  src/core/mapping/base_mapper.cc
  src/core/runtime/projection.cc
  src/core/runtime/projection.h
Labels: category:new-feature
