Repository nv-legate/legate.core, pull requests merged in 2022-11, with the labels that each got.

#459 Support for concurrent launches
  legate/core/_legion/task.py
  legate/core/communicator.py
  legate/core/launcher.py
  legate/core/operation.py
  src/core/task/task.cc
  src/core/task/task.h
  typings/legion_cffi/lib.pyi
Labels: category:improvement

#458 Some quality-of-life changes
  src/core/utilities/span.h
  src/core/utilities/type_traits.h
Labels: category:task

#462 Missing LEGATE_ABORT
  src/core/mapping/base_mapper.cc
Labels: category:task

#461 Call bind.sh unconditionally
  bind.sh
  legate/driver/command.py
  tests/unit/legate/driver/test_command.py
Labels: category:task

#455 Make `install.py` reconfigure editable installs when build type changes
  BUILD.md
  install.py
  legate/util/fs.py
  scripts/build-install.sh
  scripts/build-no-install.sh
  scripts/build-separately-no-install.sh
  scripts/build-with-legion-no-install.sh
  scripts/build-with-legion-separately-no-install.sh
  scripts/util/uninstall-global-legion-and-legate-core.sh
Labels: category:bug-fix

#467 legate/core/types: add missing `to_pandas_type` on Complex types
  legate/core/types.py
Labels: category:improvement

#460 Python optimization experiments
  legate/core/constraints.py
  legate/core/operation.py
  legate/core/partition.py
  legate/core/shape.py
Labels: category:task

#465 fix for -ll:networks none, we will init MPI if it has not been initialized
  src/core/comm/coll.cc
Labels: category:bug-fix

#469 Add option to have per-file, per-stage test overrides
  legate/tester/__init__.py
  legate/tester/stages/test_stage.py
Labels: category:task

#450 Construct region-backed 0D stores in a correct way
  legate/core/launcher.py
  legate/core/runtime.py
  legate/core/store.py
Labels: category:bug-fix

#473 Show provenance strings in the progress logs
  src/core/runtime/runtime.cc
Labels: category:task

#471 Use bind.sh for all rank detection
  bind.sh
  legate/driver/args.py
  legate/driver/command.py
  legate/driver/config.py
  legate/driver/driver.py
  legate/driver/launcher.py
  legate/driver/logs.py
  legate/jupyter/config.py
  tests/unit/legate/driver/test_args.py
  tests/unit/legate/driver/test_command.py
  tests/unit/legate/driver/test_config.py
  tests/unit/legate/driver/test_launcher.py
  tests/unit/legate/jupyter/test_config.py
Labels: category:task

#474 Print build start and end times in a conda build
  conda/conda-build/build.sh
Labels: category:task

#477 Pass a sufficiently high default value for gasnet's ibv-max-hcas
  install.py
Labels: category:bug-fix

#464 Support for library specific annotations
  legate/core/__init__.py
  legate/core/context.py
  legate/core/operation.py
Labels: category:new-feature

#475 Add --cprofile driver option
  bind.sh
  legate/driver/args.py
  legate/driver/command.py
  legate/driver/config.py
  legate/jupyter/config.py
  tests/unit/legate/driver/test_command.py
  tests/unit/legate/driver/test_config.py
  tests/unit/legate/jupyter/test_config.py
Labels: category:improvement

#472 Optimize scalar extraction
  legate/core/runtime.py
  src/core/runtime/runtime.cc
  src/core/task/return.cc
  src/core/task/return.h
  src/core/task/task.h
Labels: category:improvement

#479 Make overlap check tight
  legate/core/store.py
Labels: category:bug-fix

#468 Refactor CPU collective communicator
  legate_core_cpp.cmake
  src/core/comm/allgather_thread_local.cc
  src/core/comm/allgather_thread_mpi.cc
  src/core/comm/alltoall_thread_local.cc
  src/core/comm/alltoall_thread_mpi.cc
  src/core/comm/alltoallv_thread_local.cc
  src/core/comm/alltoallv_thread_mpi.cc
  src/core/comm/bcast_thread_mpi.cc
  src/core/comm/coll.cc
  src/core/comm/coll.h
  src/core/comm/comm_cpu.cc
  src/core/comm/gather_thread_mpi.cc
  src/core/comm/local_comm.cc
  src/core/comm/mpi_comm.cc
Labels: category:improvement

#481 Conda env script fixes
  scripts/generate-conda-envs.py
Labels: category:bug-fix

#478 Refactoring changes
  legate/core/partition.py
  legate/core/runtime.py
  legate/core/store.py
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
  src/core/mapping/core_mapper.cc
  src/core/runtime/projection.cc
Labels: category:improvement

#361 Cycle detection check
  legate/core/cycle_detector.py
  legate/core/runtime.py
  tests/unit/legate/test_cycle_check.py
Labels: category:improvement

#482 Fixes for mypy>=0.990
  .pre-commit-config.yaml
  legate/core/_legion/util.py
  legate/core/constraints.py
  pyproject.toml
  tests/unit/legate/util/test_args.py
  tests/unit/legate/util/test_types.py
Labels: category:task

#485 Fix some typos
  legate/core/launcher.py
  legate/core/store.py
Labels: category:bug-fix

#488 fix several reference cycle / leak related bugs
  legate/core/partition.py
  legate/core/runtime.py
  legate/core/store.py
Labels: category:bug-fix

#486 Regenerate `install_info.py` on every build
  CMakeLists.txt
  cmake/generate_install_info_py.cmake
  legate_core_python.cmake
  scripts/build-install.sh
  scripts/build-no-install.sh
  scripts/build-separately-no-install.sh
  scripts/build-with-legion-no-install.sh
  scripts/build-with-legion-separately-no-install.sh
Labels: category:improvement

#489 Don't filter out cycles going through __globals__
  legate/core/cycle_detector.py
Labels: category:task

#487 Update create_buffer to use socket memories whenever available
  src/core/data/buffer.h
  src/core/legate_c.h
  src/core/mapping/core_mapper.cc
  src/core/runtime/runtime.cc
  src/core/runtime/runtime.h
  src/core/task/return.h
  src/core/utilities/machine.cc
  src/core/utilities/machine.h
Labels: category:improvement

#492 Don't use cmake 3.25.0 in build-isolation mode
  pyproject.toml
Labels: category:task

#490 Throw an error if an allocation is not consumed
  legate/core/allocation.py
Labels: category:task

#495 legate/core: fix FutureMap leak in communicator shutdown
  legate/core/communicator.py
Labels: category:bug-fix

#494 Add type for LegateDataInterface
  legate/core/corelib.py
  legate/core/legate.py
  legate/core/runtime.py
  legate/jupyter/_legion_kernel.py
  legate/jupyter/magic.py
  legate/tester/args.py
  legate/timing/timing.py
  tests/unit/legate/util/test_ui.py
Labels: category:task

#496 Check for cycles involving Futures after runtime shutdown
  legate/core/cycle_detector.py
  legate/core/runtime.py
Labels: category:improvement

#499 src/core/mapping: adjust indirect copy mapping for GPUs
  src/core/mapping/base_mapper.cc
Labels: category:bug-fix

#498 legate/core: guard deletion in reset_{store,storage}_key_partition
  legate/core/runtime.py
Labels: category:task

#493 src/core/mapping: temporary fix to base_mapper for collective branch
  src/core/mapping/base_mapper.cc
Labels: category:task

#503 Don't access stream pools unless we're on GPUs
  src/core/task/return.cc
Labels: category:bug-fix

#504 Add typing-extensions run export to conda build
  conda/conda-build/meta.yaml
Labels: category:task
