Repository nv-legate/legate.core, pull requests merged in 2022-09, with the labels that each got.

#355 Use Legion primitives to coordinate accesses to the shared instance manager
  src/core/mapping/base_mapper.cc
  src/core/mapping/instance_manager.cc
  src/core/mapping/instance_manager.h
Labels: category:bug-fix

#339 Use conda build in CI
  .github/workflows/ci.yml
  conda/conda-build/meta.yaml
  install.py
Labels: category:task

#357 Fix typo in class name
  src/core/data/store.h
  src/core/data/store.inl
Labels: category:task

#356 Support for mapper logging
  src/core/runtime/context.cc
  src/core/runtime/context.h
  src/core/runtime/runtime.cc
  src/core/runtime/runtime.h
Labels: category:new-feature

#358 Synchronize instance manager accesses from mapper calls other than `map_task`
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:bug-fix

#353 A custom task wrapper for efficient handling of return values
  legate/core/runtime.py
  src/core/data/store.cc
  src/core/data/store.h
  src/core/data/store.inl
  src/core/legate_c.h
  src/core/mapping/core_mapper.cc
  src/core/runtime/context.cc
  src/core/runtime/runtime.cc
  src/core/task/return.cc
  src/core/task/return.h
  src/core/task/task.h
Labels: category:improvement

#360 Follow-on changes to #353
  src/core/mapping/core_mapper.cc
  src/core/task/return.cc
Labels: category:bug-fix

#363 Refactoring to make the runtime object singleton
  legate/core/__init__.py
  legate/core/allocation.py
  legate/core/communicator.py
  legate/core/context.py
  legate/core/io.py
  legate/core/launcher.py
  legate/core/operation.py
  legate/core/partition.py
  legate/core/restriction.py
  legate/core/runtime.py
  legate/core/solver.py
  legate/core/store.py
  legate/core/transform.py
Labels: category:improvement

#362 Turn off the precise stacktrace capturing by default
  src/core/mapping/core_mapper.cc
Labels: category:improvement

#365 Scalar store fix
  legate.py
  legate/core/launcher.py
  legate/core/store.py
Labels: category:bug-fix

#368 InstanceManager segfault fixes
  src/core/mapping/instance_manager.cc
Labels: category:bug-fix

#380 Add GitHub changelog configuration
  .github/release.yml
Labels: category:task

#382 Update mapper for AutoLock change in Legion
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:task

#381 Delay label checking on fresh PRs
  .github/workflows/require-labels.yml
Labels: category:task

#370 Provenance tracking
  legate/core/__init__.py
  legate/core/_legion/operation.py
  legate/core/_legion/task.py
  legate/core/context.py
  legate/core/launcher.py
  legate/core/operation.py
  typings/legion_cffi/lib.pyi
Labels: category:new-feature

#369 Add Fill operation
  legate/core/_legion/geometry.py
  legate/core/context.py
  legate/core/launcher.py
  legate/core/operation.py
Labels: category:new-feature

#384 Support building with GASNet-Ex and MPI backends
  README.md
  cmake/Modules/legate_core_options.cmake
  cmake/thirdparty/get_legion.cmake
  install.py
  legate/__main__.py
  legate_core_cpp.cmake
  src/core/comm/coll.cc
  src/core/comm/coll.h
  src/core/comm/comm_cpu.cc
  src/core/runtime/runtime.cc
  src/legate_defines.h
Labels: category:improvement

#366 Fix typos in solver.py
  legate/core/solver.py
Labels: category:bug-fix

#364 Better store management
  legate/core/operation.py
  legate/core/runtime.py
  legate/core/shape.py
  legate/core/solver.py
  legate/core/store.py
  src/core/legate_c.h
  src/core/mapping/core_mapper.cc
  typings/legion_cffi/lib.pyi
Labels: category:improvement

#388 Remove leftover files from old build
  src/Makefile
  src/config.mk.in
  src/core.mk
  src/legate.mk
Labels: category:task

#309 add jupyter config for legate
  README.md
  install.py
  legate/__main__.py
  legate/jupyter/__init__.py
  legate/jupyter/__main__.py
  legate/jupyter/_magic_cmd.py
  legate_jupyter.json
Labels: category:new-feature

#389 legate_core_cpp.cmake: add missing barrier header file in export
  legate_core_cpp.cmake
Labels: category:bug-fix

#391 Use Python GC to release Legion handles from destroyed RegionManagers
  legate/__init__.py
  legate/core/runtime.py
Labels: category:bug-fix

#392 Add a pool of region managers with LRU eviction
  legate/core/runtime.py
  src/core/legate_c.h
  src/core/mapping/core_mapper.cc
  typings/legion_cffi/lib.pyi
Labels: category:improvement

#394 legate/driver: fix driver legion_module path
  legate/driver/util.py
Labels: category:bug-fix

#396 Stop registering reduction ops that do not exist in Legion
  legate/core/types.py
Labels: category:task

#404 Run CI on schedule
  .github/workflows/ci.yml
Labels: category:task

#402 Adjust consensus match frequency based on field sizes
  legate/core/runtime.py
Labels: category:improvement

#406 Adjust consensus match frequency based on field sizes (#402)
  legate/core/runtime.py
Labels: category:task

#403 Driver verbose only for rank 0 or "none" launcher
  legate/driver/driver.py
  tests/unit/legate/driver/test_driver.py
Labels: category:improvement
