Repository nv-legate/legate.core, pull requests merged in 2022-10, with the labels that each got.

#409 Legion bug WAR: don't instantiate futures on framebuffer
  src/core/data/store.cc
  src/core/mapping/base_mapper.cc
  src/legate_defines.h
Labels: category:bug-fix

#413 Legion bug WAR: don't instantiate futures on framebuffer
  src/core/data/store.cc
  src/core/mapping/base_mapper.cc
  src/legate_defines.h
Labels: category:bug-fix

#414 Adjust the schedule of the CI runs
  .github/workflows/ci.yml
Labels: category:task

#416 Handle conflicts for library-level args
  legate/util/args.py
  tests/unit/legate/util/test_args.py
Labels: category:bug-fix

#418 Revive dead region managers on field allocations
  legate/core/runtime.py
  src/core/mapping/core_mapper.cc
Labels: category:bug-fix

#419 Revive dead region managers on field allocations (#418)
  legate/core/runtime.py
  src/core/mapping/core_mapper.cc
Labels: category:task

#420 Fix typo in driver script
  legate/driver/logs.py
Labels: category:task

#421 Fix typo in driver script
  legate/driver/logs.py
Labels: category:task

#423 On mapping failure retry after tightening non-RO reqs
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:improvement

#424 On mapping failure retry after tightening non-RO reqs
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:improvement

#427 Fix Transform class hierarchy
  legate/core/transform.py
Labels: category:bug-fix

#417 More changes for provenance
  legate/core/_legion/operation.py
  legate/core/store.py
  src/core/mapping/base_mapper.cc
  typings/legion_cffi/lib.pyi
Labels: category:improvement

#432 Handle scalar outputs correctly in manual tasks
  legate/core/operation.py
  src/core/task/task.h
Labels: category:bug-fix

#411 Explicitly build Legion if `legion_dir` or `legion_src_dir` is not provided
  cmake/thirdparty/get_legion.cmake
  install.py
Labels: category:bug-fix

#433 Fix GPU shard computation
  legate/tester/stages/_linux/gpu.py
  tests/unit/legate/tester/stages/_linux/test_gpu.py
Labels: category:bug-fix

#379 Only set default CMake generator if Ninja is available: Issue #374
  install.py
Labels: category:bug-fix

#434 Fix an issue with editable installs
  legate/util/fs.py
  tests/unit/legate/driver/test_main.py
Labels: category:bug-fix

#387 Allow only one of --legion-dir and --legion-src-dir
  install.py
Labels: category:bug-fix

#436 Report pytest exit code on fail
  legate/tester/stages/util.py
  legate/util/ui.py
  tests/unit/legate/tester/stages/test_util.py
  tests/unit/legate/util/test_ui.py
Labels: category:task

#437 API to declare tasks with side effects
  legate/core/operation.py
Labels: category:task

#438 legate/util: fix a mypy error on MacOS
  legate/util/system.py
Labels: category:bug-fix

#443 Missing APIs from #437
  legate/core/operation.py
Labels: category:task

#431 Support python coverage test.
  legate/tester/args.py
  legate/tester/config.py
  legate/tester/stages/test_stage.py
  tests/unit/legate/tester/stages/test_test_stage.py
  tests/unit/legate/tester/test_config.py
Labels: category:task

#445 Make terminal colors explicitly opt-in
  legate/driver/args.py
  legate/driver/config.py
  legate/jupyter/args.py
  legate/jupyter/config.py
  legate/tester/args.py
  legate/tester/config.py
  legate/util/colors.py
  tests/unit/legate/driver/test_config.py
  tests/unit/legate/jupyter/test_config.py
  tests/unit/legate/tester/test_config.py
  tests/unit/legate/util/test_colors.py
Labels: category:task

#446 Update version number
  CMakeLists.txt
Labels: category:task

#451 Remove unnecessary exec bit
  legate/driver/args.py
  legate/jupyter/args.py
  legate/lgpatch.py
Labels: category:task

#453 Fix for cunumeric#668
  legate_core_cpp.cmake
Labels: category:bug-fix

#454 Update upload artifact action version
  .github/workflows/ci.yml
Labels: category:task

#447 Only keep traceback reprs, to avoid cycles
  legate/core/exception.py
  legate/core/operation.py
  legate/core/runtime.py
  legate/core/utils.py
Labels: category:bug-fix

#456 Fix up mypy errors in tests
  .pre-commit-config.yaml
  legate/tester/stages/test_stage.py
  tests/unit/legate/driver/test_config.py
  tests/unit/legate/jupyter/test_kernel.py
  tests/unit/legate/tester/stages/test_test_stage.py
  tests/unit/legate/tester/stages/test_util.py
  tests/unit/legate/util/test_system.py
Labels: category:task

#442 Fix returned legion paths for editable install with separate legion b…
  legate/util/fs.py
Labels: category:bug-fix

#452 Mapper improvements
  legate/core/_legion/operation.py
  legate/core/launcher.py
  legate/core/operation.py
  legate_core_cpp.cmake
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
  src/core/mapping/mapping.cc
  src/core/mapping/mapping.h
  src/core/mapping/operation.cc
  src/core/mapping/operation.h
  src/core/mapping/operation.inl
  src/core/utilities/deserializer.cc
  src/core/utilities/deserializer.h
  src/core/utilities/deserializer.inl
  typings/legion_cffi/lib.pyi
Labels: category:improvement
