Repository nv-legate/legate.core, pull requests merged in 2023-07, with the labels that each got.

#778 Bump the Legion commit for a fix for multi-node runs
  cmake/versions.json
  conda/conda-build/build.sh
  install.py
  scripts/generate-conda-envs.py
Labels: category:task

#745 Opt-out validation for C++ accessor types and dimension
  examples/hello/src/square.cc
  examples/hello/src/sum.cc
  src/core/data/store.h
  src/core/data/store.inl
Labels: category:improvement

#775 Use ctypes to dlopen, for better error messages and Windows support
  legate/core/utils.py
Labels: category:task

#782 Constrain OpenBLAS version, to work around legion#1500
  scripts/generate-conda-envs.py
Labels: category:bug-fix

#781 Bump Legion version to get complex/half fix
  cmake/versions.json
Labels: category:task

#784 More error checking for stores
  src/core/data/store.cc
  src/core/data/store.h
  src/core/data/store.inl
Labels: category:improvement

#785 Use stable UIDs for common fixed-size array types
  docs/legate/core/source/api/runtime.rst
  legate/core/_lib/types.pyx
  legate/core/launcher.py
  legate/core/operation.py
  legate/core/runtime.py
  legate/core/types.pyi
  src/core/runtime/runtime.cc
  src/core/type/type_info.cc
  src/core/type/type_info.h
  tests/unit/legate/core/test_invalid_scalar_arg.py
  tests/unit/legate/core/test_type_cache.py
  tests/unit/legate/core/test_type_uid.py
Labels: category:improvement

#787 Bump Legion, to get reservation fix
  cmake/versions.json
Labels: category:task

#786 Use ordered future map reductions by default
  legate/core/_legion/future.py
  legate/core/runtime.py
Labels: category:task

#790 avoid using nvtx domain separator @ in nvtx ranges
  src/core/task/task.cc
Labels: category:bug-fix

#791 Pin host compilers to 11.* during environment generation
  scripts/generate-conda-envs.py
Labels: category:bug-fix

#788 GH, docker based (reusable) workflows
  .dockerignore
  .github/workflows/ci-gh-cpu-build-and-test.yml
  .github/workflows/ci-gh-gpu-build-and-test.yml
  .github/workflows/gh-build.yml
  .github/workflows/gh-cleanup.yml
  .github/workflows/gh-test.yml
  .gitignore
  continuous_integration/Dockerfile
  continuous_integration/home/coder/.local/bin/activate-conda-env
  continuous_integration/home/coder/.local/bin/build-all
  continuous_integration/home/coder/.local/bin/copy-artifacts
  continuous_integration/home/coder/.local/bin/entrypoint
  continuous_integration/home/coder/.local/bin/make-conda-env
  continuous_integration/home/coder/.local/bin/run-test-or-analysis
Labels: category:task

#792 revert sharding change
  legate/tester/stages/test_stage.py
Labels: category:task

#793 Disable NGC testing since the GH workflows can now do the same thing.
  .github/workflows/ci.yml
Labels: category:task

#794 Unifying GH CI conda utility functions.
  continuous_integration/Dockerfile
  continuous_integration/home/coder/.local/bin/activate-conda-env
  continuous_integration/home/coder/.local/bin/conda-utils
  continuous_integration/home/coder/.local/bin/get-yaml-and-make-conda-env
  continuous_integration/home/coder/.local/bin/run-test-or-analysis
Labels: category:task

#798 Pin cuda-version in meta.yaml
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#800 pin cuda-version
  conda/conda-build/meta.yaml
Labels: category:task

#797 Bump up the version of legate.core
  CMakeLists.txt
Labels: category:task

#806 Remove obsolete pyarrow stub
  typings/pyarrow/__init__.pyi
  typings/pyarrow/lib.pyi
Labels: category:task
