Repository nv-legate/legate.core, pull requests merged in 2023-11, with the labels that each got.

#878 Remove extraneous PYTHONPATH entry
  legate/driver/launcher.py
Labels: category:task

#882 control ucx presence in install_info more carefully
  tests/unit/legate/driver/test_command.py
Labels: category:bug-fix

#880 Typos
  scripts/util/build-caching.sh
Labels: category:task

#881 Suggest using mamba over conda
  BUILD.md
  README.md
Labels: category:documentation

#884 Fix OSX mypy errors
  legate/tester/stages/__init__.py
  legate/tester/stages/_osx/gpu.py
Labels: bug, category:bug-fix

#885 adding a workaround for NumPy's conversion from unit64 to float
  legate/core/store.py
Labels: category:bug-fix

#876 Mac CI
  .github/workflows/ci-gh-build-release.yml
  .github/workflows/ci-gh-cpu-build-and-test.yml
  .github/workflows/ci-gh-gpu-build-and-test.yml
  .github/workflows/ci-gh.yml
  .github/workflows/gh-build-and-test.yml
  .github/workflows/gh-build.yml
  .github/workflows/gh-cleanup.yml
  .github/workflows/gh-test.yml
  .gitignore
  conda/conda-build/build.sh
  conda/conda-build/meta.yaml
  continuous_integration/Dockerfile
  continuous_integration/build-docker-image
  continuous_integration/home/coder/.gitconfig
  continuous_integration/home/coder/.local/bin/build-legate
  continuous_integration/home/coder/.local/bin/conda-utils
  continuous_integration/home/coder/.local/bin/copy-artifacts
  continuous_integration/home/coder/.local/bin/entrypoint
  continuous_integration/post_py.patch
  continuous_integration/scripts/build-legate
  continuous_integration/scripts/build-legate-conda
  continuous_integration/scripts/build-legate-cpp
  continuous_integration/scripts/build-legate-wheel
  continuous_integration/scripts/conda-utils
  continuous_integration/scripts/make-conda-env
  continuous_integration/scripts/run-test-or-analysis
  continuous_integration/scripts/setup-utils
  continuous_integration/scripts/vault-s3-init
  scripts/replicate-ci.sh
Labels: category:task

#887 Add more details to conda install process
  README.md
Labels: category:documentation

#892 Restrict to cuTensor 1.X (2.X has a different API)
  scripts/generate-conda-envs.py
Labels: category:bug-fix

#890 Enable ucx in legate.core builds.
  .github/workflows/ci-gh-build-release.yml
  .github/workflows/gh-build-and-test.yml
  .github/workflows/gh-build.yml
  .github/workflows/gh-test.yml
  conda/conda-build/conda_build_config.yaml
  conda/conda-build/meta.yaml
  continuous_integration/scripts/build-legate-conda
  continuous_integration/scripts/build-legate-cpp
  continuous_integration/scripts/conda-utils
  continuous_integration/scripts/run-test-or-analysis
Labels: category:improvement

#866 Drop compilers and OpenMPI from conda env generator
  BUILD.md
  scripts/generate-conda-envs.py
Labels: category:documentation

#893 Add pointer to issue discussing cuTensor API bump
  scripts/generate-conda-envs.py
Labels: category:documentation
