Repository nv-legate/legate.core, pull requests merged in 2023-01, with the labels that each got.

#523 Update env gen script so OS type works for mac
  scripts/generate-conda-envs.py
Labels: bug, category:bug-fix

#524 Switch docs from recommonmark to myst-parser
  BUILD.md
  docs/legate/core/source/BUILD.md
  docs/legate/core/source/conf.py
  docs/legate/core/source/index.rst
  scripts/generate-conda-envs.py
Labels: category:task

#525 Remove realm pylib check
  legate/driver/launcher.py
Labels: category:task

#521 More changes to map futures to zero-copy memory
  src/core/data/store.cc
  src/core/mapping/base_mapper.cc
  src/core/mapping/core_mapper.cc
Labels: category:task

#526 Don't check for collective behavior when we have WRITE privilege
  src/core/mapping/base_mapper.cc
Labels: category:bug-fix

#528 All NCCL ranks on the same node must get the same NCCL_IB_HCA
  bind.sh
Labels: category:bug-fix

#527 legate/core/_legion: add default new argument to dep part functions
  legate/core/_legion/partition_functor.py
Labels: category:bug-fix

#533 Don't turn on Legate debug checks on debug-rel builds
  legate_core_cpp.cmake
Labels: category:bug-fix

#534 src/core: guard against missing projection functors in collective check
  src/core/mapping/base_mapper.cc
  src/core/runtime/projection.cc
  src/core/runtime/projection.h
Labels: category:bug-fix

#536 Erase cached reduction instances that cannot be acquired
  src/core/mapping/base_mapper.cc
  src/core/mapping/instance_manager.cc
  src/core/mapping/instance_manager.h
Labels: category:bug-fix

#529 Pass `CMAKE_GENERATOR` to scikit-build
  install.py
Labels: category:improvement

#538 Change the default CPU architecture to haswell.
  install.py
Labels: category:improvement

#535 Build rust `legion_prof`
  cmake/thirdparty/get_legion.cmake
  conda/conda-build/meta.yaml
  scripts/generate-conda-envs.py
Labels: category:improvement

#532 adding logic for collective instances to the legate_select_sources
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:improvement

#544 Temporarily disable collectives, to work around CI failures
  cmake/Modules/legate_core_options.cmake
Labels: category:task

#516 Add support for building Legion with the UCX backend
  BUILD.md
  CMakeLists.txt
  README.md
  install.py
  legate/driver/command.py
  legate/driver/launcher.py
  scripts/generate-conda-envs.py
  src/legate_defines.h
  tests/unit/legate/driver/test_command.py
Labels: category:improvement

#537 CLI help for library options
  legate/__init__.py
  legate/args.py
  legate/core/runtime.py
  legate/driver/args.py
  legate/rc.py
Labels: category:task

#545 Update the architectures built in conda package
  conda/conda-build/build.sh
Labels: category:improvement

#546 Update the architectures built in conda package (backport #545)
  conda/conda-build/build.sh
Labels: category:improvement

#539 Default python interpreter support for Legate
  legate/core/__init__.py
  legate/driver/__init__.py
  legate/driver/args.py
  legate/driver/command.py
  legate/driver/config.py
  legate/driver/driver.py
  legate/driver/main.py
  legate/jupyter/config.py
  legate/jupyter/kernel.py
  legate/jupyter/main.py
  legate/rc.py
  legate/util/shared_args.py
  tests/unit/legate/driver/test_command.py
  tests/unit/legate/driver/test_config.py
  tests/unit/legate/driver/test_driver.py
  tests/unit/legate/driver/test_main.py
  tests/unit/legate/jupyter/test_kernel.py
  tests/unit/legate/jupyter/test_main.py
  tests/unit/legate/test_rc.py
  typings/legion_cffi/__init__.pyi
  typings/legion_top/__init__.pyi
Labels: category:new-feature

#550 Revert "Update the architectures built in conda package (#545) (#546)"
  conda/conda-build/build.sh
Labels: category:task

#547 Fix the default Legion version
  install.py
Labels: category:task

#553 pre-commit autoupdate
  .pre-commit-config.yaml
Labels: category:task

#543 Use @loader_path instead of $ORIGIN on MacOS
  legate_core_cpp.cmake
Labels: category:task

#549 Report version info in --verbose outupt
  install.py
  legate/driver/driver.py
Labels: category:task
