Repository nv-legate/legate.core, pull requests merged in 2023-03, with the labels that each got.

#598 Re-enable collectives
  cmake/Modules/legate_core_options.cmake
Labels: category:task

#597 Fixes for running cuNumeric CI multi-node
  legate/core/store.py
  src/core/runtime/runtime.cc
Labels: category:bug-fix

#595 Remove support for python 3.8
  BUILD.md
  conda/conda-build/conda_build_config.yaml
  scripts/generate-conda-envs.py
  setup.cfg
  setup.py
Labels: category:task

#594 Set sphinx theme minver to 0.13
  scripts/generate-conda-envs.py
Labels: category:task

#592 Fix ucx:tls_host default value
  legate/driver/command.py
Labels: category:bug-fix

#599 Add CTK stubs dir to implicit link directories
  cmake/thirdparty/get_legion.cmake
  legate_core_cpp.cmake
Labels: category:improvement

#563 API reference
  cmake/Modules/legate_core_options.cmake
  docs/legate/core/Makefile
  docs/legate/core/source/api/allocation.rst
  docs/legate/core/source/api/classes.rst
  docs/legate/core/source/api/index.rst
  docs/legate/core/source/api/operation.rst
  docs/legate/core/source/api/routines.rst
  docs/legate/core/source/api/runtime.rst
  docs/legate/core/source/api/shape.rst
  docs/legate/core/source/api/store.rst
  install.py
  legate/core/allocation.py
  legate/core/context.py
  legate/core/legate.py
  legate/core/operation.py
  legate/core/resource.py
  legate/core/runtime.py
  legate/core/shape.py
  legate/core/store.py
  legate_core_cpp.cmake
  scripts/generate-conda-envs.py
  src/core/comm/communicator.h
  src/core/cuda/stream_pool.h
  src/core/data/allocator.h
  src/core/data/buffer.h
  src/core/data/scalar.cc
  src/core/data/scalar.h
  src/core/data/store.h
  src/core/mapping/mapping.cc
  src/core/mapping/mapping.h
  src/core/mapping/operation.h
  src/core/runtime/context.h
  src/core/runtime/runtime.h
  src/core/task/exception.h
  src/core/task/registrar.h
  src/core/task/task.h
  src/core/task/variant.h
  src/core/utilities/debug.h
  src/core/utilities/dispatch.h
  src/core/utilities/span.h
  src/core/utilities/type_traits.h
  src/core/utilities/typedefs.h
  src/legate.h
Labels: category:documentation

#601 Add a link to the C++ API reference in the Python doc
  docs/legate/core/source/index.rst
Labels: category:task

#600 add support for --version
  legate/driver/args.py
Labels: category:task

#603 Fix a bug in the new registration callback API
  legate_core_cpp.cmake
  src/core/runtime/runtime.cc
  src/core/runtime/runtime.h
  src/core/runtime/runtime.inl
Labels: category:bug-fix

#605 Add missing install file
  legate_core_cpp.cmake
Labels: category:task

#571 Build helper functions for legate projects, legate-hello example
  CMakeLists.txt
  cmake/legate_helper_functions.cmake
  examples/CMakeLists.txt
  examples/hello/CMakeLists.txt
  examples/hello/README.md
  examples/hello/editable-install.sh
  examples/hello/examples/cunumeric-variance.py
  examples/hello/examples/hello-world.md
  examples/hello/examples/hello-world.py
  examples/hello/examples/variance.md
  examples/hello/examples/variance.py
  examples/hello/hello/__init__.py
  examples/hello/hello/hello.py
  examples/hello/install.sh
  examples/hello/setup.py
  examples/hello/src/CMakeLists.txt
  examples/hello/src/hello_cffi.h
  examples/hello/src/hello_world.cc
  examples/hello/src/hello_world.h
  examples/hello/src/iota.cc
  examples/hello/src/square.cc
  examples/hello/src/sum.cc
  legate_core_cpp.cmake
  pyproject.toml
  src/core/runtime/runtime.h
Labels: category:improvement

#593 Pin Legion to specific commit sha by default
  CMakeLists.txt
  cmake/thirdparty/get_legion.cmake
  cmake/versions.json
  install.py
Labels: category:improvement

#606 Small fixes to README
  README.md
  docs/figures/vision.png
Labels: category:task

#610 Tutorial editable install fix
  cmake/legate_helper_functions.cmake
  examples/hello/setup.py
Labels: category:bug-fix

#608 Add support for Python 3.11
  conda/conda-build/conda_build_config.yaml
  scripts/generate-conda-envs.py
  setup.py
Labels: enhancement, category:improvement

#612 Restrict gcc versions to match nvcc compatibility
  scripts/generate-conda-envs.py
Labels: category:task

#617 Make lgpatch UX consistent with driver
  legate/lgpatch.py
Labels: category:bug-fix

#616 Avoid packaging dependency in conda env generate script
  scripts/generate-conda-envs.py
Labels: category:task

#615 Add support for Python 3.11 (#608)
  conda/conda-build/conda_build_config.yaml
  scripts/generate-conda-envs.py
  setup.py
Labels: category:improvement

#621 remove generic create_task
  legate/core/context.py
Labels: category:task

#622 Update Legion SHA (bug fix in Legion)
  cmake/versions.json
Labels: category:task

#624 v23.03.00
  cmake/versions.json
Labels: category:task

#623 Switch to rapids-cmake 23.04 early
  CMakeLists.txt
Labels: category:task

#625 Docs updates
  docs/legate/core/source/api/runtime.rst
  docs/legate/core/source/conf.py
  docs/legate/core/source/index.rst
  docs/legate/core/source/versions.rst
Labels: category:task

#628 Update info on using standard python interpreter
  README.md
Labels: category:documentation

#627 Rename variables and functions to make them clearer
  src/core/data/store.cc
  src/core/data/store.h
  src/core/data/store.inl
  src/core/mapping/mapping.cc
  src/core/mapping/mapping.h
  src/core/runtime/context.cc
  src/core/utilities/deserializer.cc
  src/core/utilities/deserializer.h
Labels: category:improvement

#626 Use subsumption checks for instance policies
  src/core/mapping/instance_manager.cc
  src/core/mapping/mapping.cc
  src/core/mapping/mapping.h
Labels: category:improvement

#630 Start discarding instances for free fields
  legate/core/_legion/operation.py
  legate/core/_legion/util.py
  legate/core/runtime.py
  typings/legion_cffi/lib.pyi
Labels: category:improvement

#634 Update Conda build scripts
  conda/conda-build/conda_build_config.yaml
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#635 Disable scheduled builds
  .github/workflows/ci.yml
Labels: category:improvement

#638 Add docs linkcheck job
  BUILD.md
  CONTRIBUTING.md
  README.md
  docs/legate/core/Makefile
Labels: category:task

#637 add --info command line option
  legate/driver/args.py
  legate/install_info.py.in
  legate/util/args.py
  legate/util/info.py
  legate_core_python.cmake
  tests/unit/legate/driver/test_args.py
  tests/unit/legate/util/test_args.py
Labels: category:task

#618 More robust nsys --sample flag with --nsys-extra
  legate/driver/command.py
  tests/unit/legate/driver/test_command.py
Labels: category:bug-fix

#646 Fix example build tests
  CMakeLists.txt
  cmake/legate_helper_functions.cmake
  examples/CMakeLists.txt
  install.py
  legate_core_cpp.cmake
Labels: category:bug-fix

#654 Add provenance information to nvtx ranges
  src/core/task/task.cc
Labels: category:improvement
