Repository nv-legate/legate.core, pull requests merged in 2023-06, with the labels that each got.

#744 Renamed workflow files.
  .github/workflows/ci-gh-build.yml
  .github/workflows/ci-gh-docs.yml
Labels: category:task

#747 Fix the broken unit test for machine objects
  tests/unit/legate.core/test_machine.py
Labels: category:bug-fix

#748 Stop tracking callbacks
  src/core/runtime/context.h
  src/core/runtime/context.inl
  src/core/runtime/runtime.cc
  src/core/runtime/runtime.h
  src/core/runtime/runtime.inl
Labels: category:improvement

#750 Check debug envs more carefully
  legate/driver/launcher.py
  tests/unit/legate/core/test_machine.py
  tests/unit/legate/core/test_store.py
  tests/unit/legate/driver/test_launcher.py
Labels: category:task

#746 Gh workflow unit tests
  .github/workflows/ci-gh-build-and-test.yml
Labels: category:task

#751 Remove dependency on pyarrow
  conda/conda-build/conda_build_config.yaml
  conda/conda-build/meta.yaml
  examples/reduction/setup.py
  scripts/generate-conda-envs.py
Labels: category:task

#753 Locking cuda-cudart to a major version
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#749 Add --ranks-per-node option to tester
  legate/tester/__init__.py
  legate/tester/args.py
  legate/tester/config.py
  legate/tester/stages/_linux/cpu.py
  legate/tester/stages/_linux/eager.py
  legate/tester/stages/_linux/gpu.py
  legate/tester/stages/_linux/omp.py
  legate/tester/stages/_osx/cpu.py
  legate/tester/stages/_osx/eager.py
  legate/tester/stages/_osx/omp.py
  legate/tester/stages/util.py
  tests/unit/legate/tester/stages/_linux/test_cpu.py
  tests/unit/legate/tester/stages/_linux/test_eager.py
  tests/unit/legate/tester/stages/_linux/test_gpu.py
  tests/unit/legate/tester/stages/_linux/test_omp.py
  tests/unit/legate/tester/stages/test_test_stage.py
Labels: category:improvement

#754 Remove cudatoolkit from the environment generation script
  scripts/generate-conda-envs.py
Labels: category:task

#756 Add support for test timeouts
  legate/tester/args.py
  legate/tester/config.py
  legate/tester/stages/test_stage.py
  legate/tester/stages/util.py
  legate/tester/test_plan.py
  legate/tester/test_system.py
  legate/util/ui.py
  tests/unit/legate/tester/stages/test_util.py
  tests/unit/legate/tester/test_args.py
  tests/unit/legate/tester/test_config.py
  tests/unit/legate/tester/test_test_system.py
  tests/unit/legate/util/test_ui.py
Labels: category:improvement

#758 Add support for --gasnet-system
  cmake/versions.json
  install.py
Labels: category:improvement

#761 Have each test worker stick to its original shard
  legate/tester/stages/test_stage.py
Labels: category:bug-fix

#760 Use cuda-version to constrain CTK version pulled from conda
  scripts/generate-conda-envs.py
Labels: category:task

#759 Rev up the version in cmake
  CMakeLists.txt
Labels: category:bug-fix

#757 GH (reusable) workflow for legate.core CPU+GPU builds and tests.
  .github/workflows/ci-gh-build-and-test.yml
  .github/workflows/ci-gh-cpu-build-and-test.yml
  .github/workflows/ci-gh-gpu-build-and-test.yml
  .github/workflows/gh-build.yml
  .github/workflows/gh-test.yml
  continuous_integration/home/coder/.local/bin/build-legate-conda
Labels: category:task

#763 Mapper unification
  docs/legate/core/source/api/runtime.rst
  legate/core/communicator.py
  legate/core/context.py
  legate/core/io.py
  legate/core/operation.py
  legate/core/runtime.py
  legate/core/store.py
  legate_core_cpp.cmake
  src/core/legate_c.h
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
  src/core/mapping/core_mapper.cc
  src/core/mapping/core_mapper.h
  src/core/mapping/machine.cc
  src/core/mapping/machine.h
  src/core/runtime/context.cc
  src/core/runtime/runtime.cc
  src/legate.h
  typings/legion_cffi/lib.pyi
Labels: category:improvement

#769 fix issue with newer mypy
  legate/tester/stages/test_stage.py
Labels: category:task

#764 Add nvidia to the list of channels synced in CI during testing
  .github/workflows/gh-test.yml
  continuous_integration/home/coder/.local/bin/build-legate-conda
Labels: category:bug-fix

#770 Add start/end timestamps to test results
  legate/tester/stages/util.py
  legate/tester/test_system.py
  tests/unit/legate/tester/stages/test_util.py
Labels: category:task

#772 avoid undefined behavior in `Span::end`
  src/core/utilities/span.h
Labels: category:bug-fix

#766 Set lib_dir explicitly to lib/, even on RHEL
  CMakeLists.txt
  cmake/legate_helper_functions.cmake
  legate_core_cpp.cmake
  legate_core_python.cmake
Labels: category:bug-fix

#776 usage of protocol does not work with 3.9
  scripts/generate-conda-envs.py
Labels: category:task

#774 Fix failing GH CI workflows due to environment resolution issues
  .github/workflows/gh-test.yml
Labels: in progress, category:task

#777 Add a small type cache for array-typed scalar arguments
  docs/legate/core/source/api/runtime.rst
  legate/core/launcher.py
  legate/core/runtime.py
  tests/unit/legate/core/test_type_cache.py
Labels: category:improvement
