Repository nv-legate/legate.core, pull requests merged in 2023-04, with the labels that each got.

#661 Don't use traceback.walk_stack(None)
  legate/core/context.py
Labels: category:bug-fix

#653 Guard against attaching to non-contiguous buffers
  legate/core/_legion/operation.py
  legate/core/runtime.py
Labels: category:documentation

#640 vectorize-pr
  scripts/generate-conda-envs.py
Labels: category:task

#655 Fix documentation issues
  README.md
  docs/legate/core/source/conf.py
Labels: documentation, category:documentation

#657 Skip provenance from NVTX range if empty
  src/core/task/task.cc
Labels: category:bug-fix

#656 Adding ci-gh.yml to build legate.core documentation on a github runner.
  .github/workflows/ci-gh.yml
Labels: category:documentation

#664 Switch to quarterly updates of pre-commit hooks
  .pre-commit-config.yaml
Labels: category:task

#673 Note new minimum CUDA requirements for conda packages
  README.md
Labels: category:documentation

#666 Use parent frame indiscriminately in nested provenance
  legate/core/context.py
Labels: category:improvement

#674 Remove deprecated mapping speculation calls
  cmake/versions.json
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:task

#680 Revert "Start discarding instances for free fields (#630)"
  legate/core/_legion/operation.py
  legate/core/_legion/util.py
  legate/core/runtime.py
  typings/legion_cffi/lib.pyi
Labels: category:bug-fix

#681 Safe vector accesses in examples
  .clang-format
  examples/hello/src/hello_world.cc
  examples/hello/src/iota.cc
  examples/hello/src/square.cc
  examples/hello/src/sum.cc
  examples/io/src/read_even_tiles.cc
  examples/io/src/read_file.cc
  examples/io/src/read_uneven_tiles.cc
  examples/io/src/write_even_tiles.cc
  examples/io/src/write_file.cc
  examples/io/src/write_uneven_tiles.cc
  src/.clang-format
Labels: category:improvement

#679 use legate_dir as basis for non-editable install paths
  legate/util/fs.py
Labels: category:task

#683 Adding a GH CI step for running the documentation link checker.
  .github/workflows/ci-gh.yml
Labels: category:improvement

#685 Specify C++ standard when building cython sources
  legate/core/_lib/CMakeLists.txt
Labels: category:task

#676 Mapper refactoring
  cmake/legate_helper_functions.cmake
  legate/core/_lib/context.pyx
  legate/core/context.py
  legate/core/launcher.py
  legate/core/operation.py
  legate/core/runtime.py
  legate_core_cpp.cmake
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
  src/core/mapping/core_mapper.cc
  src/core/mapping/default_mapper.cc
  src/core/mapping/default_mapper.h
  src/core/mapping/mapping.h
  src/core/mapping/operation.cc
  src/core/mapping/operation.h
  src/core/runtime/context.cc
  src/core/runtime/context.h
  src/core/runtime/runtime.cc
  src/core/runtime/runtime.h
  tests/integration/registry/src/library.cc
Labels: category:improvement

#690 `LibraryContext*` everywehere
  cmake/legate_helper_functions.cmake
  src/core/comm/comm.cc
  src/core/comm/comm.h
  src/core/comm/comm_cpu.cc
  src/core/comm/comm_cpu.h
  src/core/comm/comm_nccl.cu
  src/core/comm/comm_nccl.h
  src/core/runtime/projection.cc
  src/core/runtime/projection.h
  src/core/runtime/runtime.cc
  src/core/runtime/shard.cc
  src/core/runtime/shard.h
  src/core/task/registrar.cc
  src/core/task/registrar.h
  src/core/task/return.cc
  src/core/task/task.h
  src/core/task/task.inl
  tests/integration/registry/src/library.cc
Labels: category:task

#691 Bump up the legion commit hash to fetch the reservation fix
  cmake/versions.json
Labels: category:task

#692 Make `legate::is_floating_point` hold for float16
  src/core/utilities/type_traits.h
Labels: category:bug-fix

#689 Minor fix to make LEGATE_TEST=0 behave correctly
  src/core/mapping/base_mapper.cc
  src/core/mapping/core_mapper.cc
Labels: category:task

#671 Fix the mapping of Futures in the BaseMapper
  src/core/mapping/base_mapper.cc
Labels: category:bug-fix

#684 Document read-only / env-only settings
  docs/legate/core/source/api/index.rst
  docs/legate/core/source/api/settings.rst
  docs/legate/core/source/conf.py
  legate/_sphinxext/settings.py
  legate/settings.py
  legate/util/settings.py
  src/core/mapping/core_mapper.cc
  src/env_defaults.h
  tests/unit/legate/test_cycle_check.py
  tests/unit/legate/test_settings.py
  tests/unit/legate/util/test_settings.py
Labels: category:documentation

#639 Add per-library loggers at the python level
  cmake/versions.json
  legate/core/_legion/util.py
  legate/core/context.py
  typings/legion_cffi/lib.pyi
Labels: category:new-feature

#693 Add a missing include to cmake for legate helper functions
  legate_core_cpp.cmake
Labels: category:bug-fix

#694 Support PYTHONFAULTHANDLER
  legate/driver/launcher.py
  tests/unit/legate/driver/test_launcher.py
Labels: category:task

#688 Fix CMake template directories to use current_dir for subfolders
  .gitignore
  cmake/legate_helper_functions.cmake
Labels: category:bug-fix

#695 Bump Legion version to fix cuNumeric CI hangs
  cmake/versions.json
Labels: category:task

#696 special-case tester reporting of LEGATE_CONFIG
  legate/tester/stages/test_stage.py
  legate/tester/test_system.py
Labels: category:task

#698 Driver error if legate was compiled w/o required options
  legate/driver/command.py
  legate/install_info.py.in
  tests/unit/legate/driver/test_command.py
Labels: category:task

#700 Not all task.futures are backing Stores
  src/core/mapping/base_mapper.cc
Labels: category:bug-fix

#701 Use std::set.rbegin() instead of non-existent std::std.back()
  src/core/mapping/base_mapper.cc
Labels: category:task

#705 Add ops-bot config file
  .github/ops-bot.yaml
Labels: category:improvement
