Repository nv-legate/legate.core, pull requests merged in 2023-05, with the labels that each got.

#709 Force other packages in env to use OpenBLAS as their BLAS backend
  scripts/generate-conda-envs.py
Labels: category:task

#708 Document a case where the communicators list may be empty
  src/core/runtime/context.h
Labels: category:documentation

#686 adding flag for valgrind
  legate/driver/args.py
  legate/driver/command.py
  legate/driver/config.py
  legate/jupyter/config.py
  scripts/generate-conda-envs.py
  tests/unit/legate/driver/test_command.py
  tests/unit/legate/driver/test_config.py
  tests/unit/legate/jupyter/test_config.py
Labels: category:improvement

#697 Core type system
  examples/hello/editable-install.sh
  examples/hello/src/square.cc
  examples/hello/src/sum.cc
  examples/io/editable-install.sh
  examples/io/legateio/legateio.py
  examples/io/setup.py
  examples/io/src/read_even_tiles.cc
  examples/io/src/read_file.cc
  examples/io/src/read_uneven_tiles.cc
  examples/io/src/util.cc
  examples/io/src/write_even_tiles.cc
  examples/io/src/write_file.cc
  examples/io/src/write_uneven_tiles.cc
  legate/core/__init__.py
  legate/core/_legion/space.py
  legate/core/_lib/CMakeLists.txt
  legate/core/_lib/types.pyx
  legate/core/context.py
  legate/core/io.py
  legate/core/launcher.py
  legate/core/legate.py
  legate/core/operation.py
  legate/core/runtime.py
  legate/core/store.py
  legate/core/types.py
  legate/core/types.pyi
  legate/timing/timing.py
  legate_core_cpp.cmake
  src/core/data/scalar.cc
  src/core/data/scalar.h
  src/core/data/scalar.inl
  src/core/data/store.cc
  src/core/data/store.h
  src/core/legate_c.h
  src/core/mapping/base_mapper.cc
  src/core/mapping/mapping.cc
  src/core/mapping/mapping.h
  src/core/mapping/operation.cc
  src/core/mapping/operation.h
  src/core/runtime/context.h
  src/core/runtime/context.inl
  src/core/runtime/resource.h
  src/core/runtime/runtime.cc
  src/core/runtime/runtime.h
  src/core/runtime/runtime.inl
  src/core/type/type_info.cc
  src/core/type/type_info.h
  src/core/type/type_traits.h
  src/core/utilities/debug.cc
  src/core/utilities/deserializer.cc
  src/core/utilities/deserializer.h
  src/core/utilities/deserializer.inl
  src/core/utilities/dispatch.h
  src/core/utilities/type_traits.h
  src/core/utilities/typedefs.h
  src/legate.h
  tests/integration/registry/editable-install.sh
  typings/legion_cffi/lib.pyi
Labels: category:improvement

#711 call MPI_Init_thread when necessary
  src/core/comm/mpi_comm.cc
Labels: category:task

#713 Follow-ups from recent type system changes
  legate/core/_lib/types.pyx
  src/core/data/scalar.h
  src/core/type/type_info.cc
  src/core/type/type_info.h
Labels: category:task

#714 Fix off-by-one errors in resource scoping code
  legate/core/machine.py
  src/core/mapping/machine.cc
Labels: category:bug-fix

#707 Remove Context dependency from annotations
  docs/legate/core/source/api/runtime.rst
  legate/core/__init__.py
  legate/core/context.py
  legate/core/operation.py
  legate/core/runtime.py
  legate/core/store.py
Labels: category:task

#716 Fix a "file-not-found" bug during repeated editable installs
  cmake/legate_helper_functions.cmake
Labels: category:bug-fix

#718 Ask cuTensor for detailed error messages
  legate/driver/launcher.py
Labels: category:task

#717 Bump Legion commit, to get a bugfix related to reductions
  cmake/versions.json
Labels: category:task

#719 Minor fix for type construction in Scalar
  src/core/data/scalar.inl
Labels: category:bug-fix

#721 Propagate the fix for overzealous assertions in Legion
  cmake/versions.json
Labels: category:task

#722 Fixes for type inconsistencies
  legate/core/_lib/types.pyx
  legate/core/launcher.py
  legate/core/machine.py
  src/core/data/store.cc
  src/core/data/store.h
  src/core/utilities/deserializer.cc
  src/core/utilities/deserializer.inl
Labels: category:task

#723 Add interface files to the manifest
  MANIFEST.in
Labels: category:bug-fix

#710 Adding support for GH CI.
  .github/workflows/ci-gh1.yml
  continuous_integration/home/coder/.gitconfig
  continuous_integration/home/coder/.local/bin/build-all
  continuous_integration/home/coder/.local/bin/build-legate-conda
  continuous_integration/home/coder/.local/bin/build-legate-cpp
  continuous_integration/home/coder/.local/bin/build-legate-wheel
  continuous_integration/home/coder/.local/bin/entrypoint
  continuous_integration/home/coder/.local/bin/make-conda-env
Labels: category:task

#727 Use the NCCL workaround unconditionally
  src/core/comm/comm_nccl.cu
Labels: category:task

#729 Bump Legion version, for fix to deferred allocation-related hang
  cmake/versions.json
Labels: category:task

#731 Fix bugs in corner cases of `tree_reduce`
  examples/reduction/src/unique.cc
  legate/core/operation.py
  tests/integration/tree_reduce/examples/test_tree_reduce.py
  tests/integration/tree_reduce/src/tree_reduce_cffi.h
Labels: category:bug-fix

#732 Prioritize OMPI_ vs SLURM_ envvars when inferring rank
  bind.sh
Labels: category:task

#730 Make sure local fields are not enabled for any Python interpreter
  cmake/Modules/legate_core_options.cmake
  cmake/thirdparty/get_legion.cmake
  cmake/versions.json
  legate/driver/command.py
  tests/integration/region_manager/CMakeLists.txt
  tests/integration/region_manager/editable-install.sh
  tests/integration/region_manager/examples/test_region_manager.py
  tests/integration/region_manager/install.sh
  tests/integration/region_manager/region_manager/__init__.py
  tests/integration/region_manager/region_manager/lib.py
  tests/integration/region_manager/setup.py
  tests/integration/region_manager/src/CMakeLists.txt
  tests/integration/region_manager/src/library.cc
  tests/integration/region_manager/src/library.h
  tests/integration/region_manager/src/region_manager_cffi.h
  tests/integration/region_manager/src/tester.cc
  tests/integration/region_manager/src/tester.h
  tests/unit/legate/driver/test_command.py
Labels: category:bug-fix

#726 Fixes for resource scoping
  legate/core/machine.py
  src/core/mapping/base_mapper.cc
  src/core/runtime/shard.cc
Labels: category:bug-fix

#734 Error-out if multi-rank run is started on build w/o networking
  legate/driver/command.py
  tests/unit/legate/driver/test_command.py
  tests/unit/legate/driver/test_driver.py
  tests/unit/legate/util/test_system.py
Labels: category:improvement

#733 Don't automatically close dlopen'ed .so's of Legate libs
  legate/core/runtime.py
  legate/core/utils.py
Labels: category:bug-fix

#715 Unify env test flags
  legate/tester/stages/_linux/cpu.py
  legate/tester/stages/_linux/gpu.py
  legate/tester/stages/_linux/omp.py
  legate/tester/stages/_osx/cpu.py
  legate/tester/stages/_osx/gpu.py
  legate/tester/stages/_osx/omp.py
  legate/tester/stages/util.py
  legate/util/settings.py
  tests/unit/legate/tester/stages/_linux/test_cpu.py
  tests/unit/legate/tester/stages/_linux/test_eager.py
  tests/unit/legate/tester/stages/_linux/test_gpu.py
  tests/unit/legate/tester/stages/_linux/test_omp.py
Labels: category:task

#737 Load Legate .so's using RTLD_GLOBAL, so they're included in dlopen(NULL)
  legate/core/utils.py
Labels: category:task

#735 Don't pass UCX options when we know we're not using it
  legate/driver/command.py
  legate/driver/launcher.py
  tests/unit/legate/driver/test_command.py
Labels: category:task

#736 Add specialized constructors and safety checks to `legate::Scalar`
  src/core/data/scalar.cc
  src/core/data/scalar.h
  src/core/data/scalar.inl
Labels: category:improvement

#741 Bump up the legion commit for a Realm fix on indirect copies (back-port #740)
  cmake/versions.json
Labels: category:task

#740 Bump up the legion commit for a Realm fix on indirect copies
  cmake/versions.json
Labels: category:task

#739 Add MPI escape hatch flag
  legate/core/context.py
  legate/core/runtime.py
  legate/settings.py
  src/core/comm/comm.cc
  src/env_defaults.h
  tests/unit/legate/test_settings.py
Labels: category:task

#743 Fix error w/ disable mpi setting
  legate/core/runtime.py
Labels: category:bug-fix
