Repository nv-legate/legate.core, pull requests merged in 2023-09, with the labels that each got.

#828 Use Legion with CMake's native CUDA language
  .github/workflows/ci-gh-docs.yml
  cmake/Modules/cuda_arch_helpers.cmake
  cmake/Modules/legate_core_options.cmake
  cmake/thirdparty/get_legion.cmake
  cmake/versions.json
  conda/conda-build/build.sh
  conda/conda-build/conda_build_config.yaml
  conda/conda-build/meta.yaml
  continuous_integration/home/coder/.local/bin/build-legate-conda
  continuous_integration/home/coder/.local/bin/build-legate-cpp
  continuous_integration/home/coder/.local/bin/build-legate-wheel
  continuous_integration/home/coder/.local/bin/conda-utils
  continuous_integration/home/coder/.local/bin/copy-artifacts
  continuous_integration/home/coder/.local/bin/run-test-or-analysis
  install.py
  legate/install_info.py.in
  legate_core_cpp.cmake
  legate_core_python.cmake
  pyproject.toml
  scripts/build-install.sh
  scripts/build-no-install.sh
  scripts/build-separately-no-install.sh
  scripts/build-with-legion-no-install.sh
  scripts/build-with-legion-separately-no-install.sh
  scripts/generate-conda-envs.py
  scripts/launch-devcontainer-conda.sh
  scripts/launch-devcontainer-pip.sh
  scripts/launch-devcontainer.sh
  scripts/replicate-ci.sh
  setup.py
Labels: category:improvement

#822 updating cuda toolkit version in documentation
  BUILD.md
Labels: documentation, category:documentation

#831 Updates for latest Realm UCX backend
  cmake/versions.json
  legate/driver/launcher.py
Labels: category:task

#830 Revert accidental changes to `conda build` files
  conda/conda-build/build.sh
  conda/conda-build/conda_build_config.yaml
Labels: category:bug-fix

#832 auto-detect multi-node based on env vars
  legate/driver/args.py
  legate/util/shared_args.py
  tests/unit/legate/driver/test_args.py
Labels: category:improvement

#833 Move to CUDA 12.
  .github/workflows/gh-build.yml
  continuous_integration/Dockerfile
Labels: category:task

#835 Enabling shard-local future creation for io
  legate/core/_legion/future.py
  legate/core/io.py
  legate/core/runtime.py
  typings/legion_cffi/lib.pyi
Labels: category:bug-fix

#836 fix user-supplied PYTHONPATH
  legate/driver/launcher.py
  tests/unit/legate/driver/test_launcher.py
Labels: category:bug-fix

#823 Supporting unordered detach operation
  legate/core/_legion/operation.py
  legate/core/runtime.py
  legate/core/store.py
Labels: category:bug-fix

#819 Adding support for oversubscription
  legate/core/runtime.py
  src/core/legate_c.h
  src/core/mapping/base_mapper.cc
  src/core/mapping/machine.cc
  src/core/mapping/machine.h
  src/core/runtime/shard.cc
  tests/integration/scoping/examples/test_scoping.py
  tests/integration/scoping/src/library.cc
  tests/integration/scoping/src/scoping_cffi.h
Labels: category:bug-fix

#834 Respect the type of passed storage in create_store
  legate/core/runtime.py
Labels: category:bug-fix

#839 Use repository variables as possible.
  .github/workflows/ci-gh-cpu-build-and-test.yml
  .github/workflows/ci-gh-gpu-build-and-test.yml
  .github/workflows/gh-build.yml
  .github/workflows/gh-test.yml
Labels: in progress, category:improvement

#841 Change CUDA 11.8 to 12.0.
  .github/workflows/ci-gh-docs.yml
  BUILD.md
  README.md
  conda/conda-build/meta.yaml
Labels: category:task

#844 Update version to 23.11
  CMakeLists.txt
Labels: category:task

#845 Update Legion
  cmake/versions.json
Labels: category:task

#838 [WIP] Remove automatic log processing
  legate/driver/args.py
  legate/driver/command.py
  legate/driver/config.py
  legate/driver/driver.py
  legate/driver/logs.py
  legate/jupyter/config.py
  tests/unit/legate/driver/test_args.py
  tests/unit/legate/driver/test_command.py
  tests/unit/legate/driver/test_config.py
  tests/unit/legate/driver/test_driver.py
  tests/unit/legate/driver/test_logs.py
  tests/unit/legate/jupyter/test_config.py
Labels: category:task
