Repository nv-legate/legate.core, pull requests merged in 2023-12, with the labels that each got.

#899 Print driver output only on head nodes
  legate/driver/driver.py
  legate/driver/main.py
  tests/unit/legate/driver/test_driver.py
Labels: category:task

#901 Update version
  CMakeLists.txt
Labels: category:task

#906 Leave --march unset by default
  install.py
Labels: category:task

#907 Retarget docs build on self hosted runner
  .github/workflows/ci-gh-docs.yml
  continuous_integration/scripts/build-legate
  continuous_integration/scripts/make-conda-env
Labels: category:improvement

#898 Configure Realm to dlopen libucp
  BUILD.md
  cmake/thirdparty/get_legion.cmake
Labels: category:task

#909 Fix typo in legate help
  legate/util/shared_args.py
Labels: category:documentation

#912 Remove some irrelevant Legion build options
  install.py
Labels: category:task

#910 Use labels from the nvidia channel to restrict CTK versions
  scripts/generate-conda-envs.py
Labels: category:bug-fix

#911 Fix compilation error with std::min on MacOS
  examples/io/src/read_file.cc
Labels: category:bug-fix

#915 Don't build rust profiler by default
  cmake/thirdparty/get_legion.cmake
  install.py
Labels: category:task

#914 Add cuda-cudart-static to generated conda environments
  .github/workflows/ci-gh-build-release.yml
  .github/workflows/ci-gh-docs.yml
  .github/workflows/ci-gh.yml
  .github/workflows/gh-build-and-test.yml
  BUILD.md
  cmake/thirdparty/get_legion.cmake
  conda/conda-build/meta.yaml
  continuous_integration/scripts/build-legate
  continuous_integration/scripts/build-legate-conda
  continuous_integration/scripts/build-legate-cpp
  continuous_integration/scripts/build-legate-wheel
  continuous_integration/scripts/conda-utils
  continuous_integration/scripts/setup-utils
  scripts/conda-build.sh
  scripts/generate-conda-envs.py
  tests/unit/legate/tester/stages/test_test_stage.py
Labels: category:task

#916 Fix build of rust profiler
  cmake/thirdparty/get_legion.cmake
Labels: category:task

#917 improve multi-node detection
  legate/driver/args.py
  tests/unit/legate/driver/test_args.py
Labels: category:task

#918 SLURM_TASKS_PER_NODE is not always an integer
  legate/driver/args.py
  tests/unit/legate/driver/test_args.py
Labels: category:task

#919 handle SLURM_TASKS_PER_NODE more thoroughly
  legate/driver/args.py
  tests/unit/legate/driver/test_args.py
Labels: category:task

#920 Run docs build on self-hosted runner and container.
  .github/workflows/ci-gh-docs.yml
Labels: category:improvement
