Repository nv-legate/legate.core, pull requests merged in 2023-10, with the labels that each got.

#848 Satisfy new flake8 type check rules
  legate/core/_legion/future.py
  legate/core/_legion/region.py
  legate/core/cycle_detector.py
  legate/core/launcher.py
  legate/core/store.py
Labels: category:task

#849 Expand ranges when reading thread_siblings_list
  legate/util/system.py
  tests/unit/legate/util/test_system.py
Labels: category:improvement

#851 Use testdata to remove duplicate test dictionary
  tests/unit/legate/util/test_system.py
Labels: category:improvement

#842 Avoid gc infinite loop at runtime destruction time
  legate/core/runtime.py
Labels: category:bug-fix

#850 Add missing 12.0 CUDA libraries to env generation script
  BUILD.md
  scripts/generate-conda-envs.py
Labels: category:bug-fix

#856 Fix error: unknown docker flag --progress.
  continuous_integration/build-docker-image
Labels: category:task

#852 Document support matrix
  BUILD.md
Labels: category:documentation

#858 Remove unnecessary packages that are not available on aarch64
  scripts/generate-conda-envs.py
Labels: category:task

#859 Set Mypy version downloaded in CI
  continuous_integration/home/coder/.local/bin/run-test-or-analysis
Labels: category:bug-fix

#857 API reference for resource scoping
  docs/legate/core/source/api/classes.rst
  docs/legate/core/source/api/machine.rst
  docs/legate/core/source/api/routines.rst
  legate/core/__init__.py
  legate/core/machine.py
Labels: category:documentation

#855 Remove numpy from conda build dependencies.
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#863 Add legate-issue command for collecting issue info
  legate/issue.py
  setup.py
Labels: category:task

#865 make _lib a proper module
  legate/core/_lib/__init__.py
Labels: category:task

#825 Add a launcher option to the tester
  legate/tester/__init__.py
  legate/tester/args.py
  legate/tester/config.py
  legate/tester/stages/_linux/cpu.py
  legate/tester/stages/_linux/gpu.py
  legate/tester/stages/_linux/omp.py
  legate/tester/stages/test_stage.py
  tests/unit/legate/tester/test___init__.py
  tests/unit/legate/tester/test_args.py
  tests/unit/legate/tester/test_config.py
Labels: category:improvement

#861 Use conda for all dependencies.
  scripts/generate-conda-envs.py
Labels: category:task

#805 GH build releasables
  .github/workflows/ci-gh-build-release.yml
  .github/workflows/ci-gh-cpu-build-and-test.yml
  .github/workflows/ci-gh-gpu-build-and-test.yml
  .github/workflows/gh-build.yml
  conda/conda-build/build.sh
  conda/conda-build/conda_build_config.yaml
  conda/conda-build/meta.yaml
  continuous_integration/Dockerfile
  continuous_integration/build-docker-image
  continuous_integration/home/coder/.local/bin/build-legate
  continuous_integration/home/coder/.local/bin/build-legate-all
  continuous_integration/home/coder/.local/bin/build-legate-conda
  continuous_integration/home/coder/.local/bin/conda-utils
  continuous_integration/home/coder/.local/bin/copy-artifacts
  continuous_integration/home/coder/.local/bin/make-conda-env
Labels: category:task

#877 Create bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: category:task
