Repository nv-legate/legate.core, pull requests merged in 2023-02, with the labels that each got.

#555 Don't report cn version for now
  legate/driver/driver.py
Labels: category:task

#293 NVTX: Use RangePush and Domain
  src/core/runtime/runtime.cc
  src/core/utilities/nvtx_help.h
Labels: category:improvement

#557 Update label action to v3
  .github/workflows/require-labels.yml
Labels: category:task

#558 Remove unsuccessful label delay attempt
  .github/workflows/require-labels.yml
Labels: category:task

#562 Args and Config
  legate/core/__init__.py
  legate/driver/__init__.py
  legate/driver/args.py
  legate/driver/config.py
  legate/tester/stages/_linux/cpu.py
  legate/tester/stages/_linux/eager.py
  legate/tester/stages/_linux/gpu.py
  legate/tester/stages/_linux/omp.py
  legate/tester/stages/_osx/cpu.py
  legate/tester/stages/_osx/eager.py
  legate/tester/stages/_osx/gpu.py
  legate/tester/stages/_osx/omp.py
  legate/tester/stages/test_stage.py
  tests/unit/legate/tester/stages/_linux/test_cpu.py
  tests/unit/legate/tester/stages/_linux/test_gpu.py
  tests/unit/legate/tester/stages/_linux/test_omp.py
  tests/unit/legate/tester/stages/test_test_stage.py
Labels: category:task

#564 Add the missing documentation category to PR label check
  .github/workflows/require-labels.yml
Labels: category:task

#565 Update Build.md to add the missing dependency, rust
  BUILD.md
Labels: category:documentation

#559 Mappers should skip collective views with no suitable instance
  src/core/mapping/base_mapper.cc
Labels: category:bug-fix

#560 Bump up to Thrust 1.17
  cmake/versions.json
Labels: category:task

#567 Move RC command line args to env var / settings
  legate/__init__.py
  legate/args.py
  legate/core/runtime.py
  legate/settings.py
  legate/util/settings.py
  tests/unit/legate/test_cycle_check.py
  tests/unit/legate/test_settings.py
  tests/unit/legate/util/test_settings.py
Labels: category:task

#569 don't use sys.argv for plain python init
  legate/core/__init__.py
Labels: category:bug-fix

#566 Document DeferredBuffer.destroy() lifetime issues in CUDA tasks
  src/core/cuda/stream_pool.h
  src/core/data/buffer.h
Labels: category:documentation

#572 Updates for cmd opts -> env vars
  legate/driver/args.py
  legate/settings.py
  legate/tester/stages/_linux/cpu.py
  legate/tester/stages/_linux/eager.py
  legate/tester/stages/_linux/gpu.py
  legate/tester/stages/_linux/omp.py
  legate/tester/stages/_osx/cpu.py
  legate/tester/stages/_osx/eager.py
  legate/tester/stages/_osx/gpu.py
  legate/tester/stages/_osx/omp.py
  legate/tester/stages/test_stage.py
  legate/tester/stages/util.py
  legate/util/args.py
  tests/unit/legate/tester/stages/_linux/test_cpu.py
  tests/unit/legate/tester/stages/_linux/test_eager.py
  tests/unit/legate/tester/stages/_linux/test_gpu.py
  tests/unit/legate/tester/stages/_linux/test_omp.py
  tests/unit/legate/tester/stages/test_test_stage.py
  tests/unit/legate/util/test_args.py
Labels: category:task

#574 Fix a minor compiler warning
  src/core/utilities/machine.cc
Labels: category:task

#576 Add `--numamem` to the tester
  legate/tester/__init__.py
  legate/tester/args.py
  legate/tester/config.py
  legate/tester/stages/_linux/omp.py
  tests/unit/legate/tester/stages/_linux/test_omp.py
  tests/unit/legate/tester/test___init__.py
  tests/unit/legate/tester/test_args.py
Labels: category:bug-fix

#575 Change default --cpus value to 2
  legate/tester/__init__.py
  tests/unit/legate/tester/test___init__.py
Labels: category:task

#577 Skip python 3.9.7 to work around python issue45121
  conda/conda-build/conda_build_config.yaml
  scripts/generate-conda-envs.py
  setup.cfg
Labels: category:task

#579 Deps for cunumeric docs updates
  legate/_sphinxext/__init__.py
  legate/_sphinxext/settings.py
  pyproject.toml
  scripts/generate-conda-envs.py
Labels: category:task

#583 Add hopper to CUDA architectures
  cmake/Modules/cuda_arch_helpers.cmake
Labels: category:task

#580 Don't silently ignore non-existing user-supplied dirs
  install.py
Labels: category:task

#584 Fix driver help typos
  legate/driver/args.py
Labels: category:task

#578 Revert "NVTX: Use RangePush and Domain (#293)"
  src/core/runtime/runtime.cc
  src/core/utilities/nvtx_help.h
Labels: category:task

#586 Add nvml dependency in the conda build script to get the headers for realm
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#589 Fix non-editable build
  legate_core_cpp.cmake
Labels: category:task

#590 Runtime network detection and UCX options
  legate/driver/command.py
  legate/install_info.py.in
  legate_core_python.cmake
  tests/unit/legate/driver/test_command.py
Labels: category:task

#587 Fix is_complete_for check
  legate/core/partition.py
  legate/core/shape.py
Labels: category:bug-fix

#588 Copy warnings on stderr even if logging to file
  legate/driver/command.py
  tests/unit/legate/driver/test_command.py
Labels: category:task

#591 Fix C++ warnings, virtual destructor bugs, and style issues
  src/core/mapping/core_mapper.cc
  src/core/mapping/mapping.h
Labels: category:improvement
