Repository nv-legate/legate.core, pull requests merged in 2024-02, with the labels that each got.

#924 Add libhwloc library
  conda/conda-build/meta.yaml
  scripts/generate-conda-envs.py
Labels: in progress, category:improvement

#932 Remove unnecessary flags in Legion CMake build
  cmake/thirdparty/get_legion.cmake
  cmake/versions.json
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:task

#934 Revert "Remove unnecessary flags in Legion CMake build (#932)"
  cmake/thirdparty/get_legion.cmake
  cmake/versions.json
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:task

#935 Remove unnecessary flags in Legion CMake build (#932)
  cmake/thirdparty/get_legion.cmake
  cmake/versions.json
  src/core/mapping/base_mapper.cc
  src/core/mapping/base_mapper.h
Labels: category:improvement
